### ISSUE TITLE
Melpa stable

### ISSUE THREAD

**Issue by nlamirault** [ikirill/irony-eldoc#3]
could you please create a tag to use this package using melpa stable [1].
Thanks

[1] : http://stable.melpa.org/

**Comment by nickbroon** [comment]
:+1:
preferably after #5 is fixed.

**Comment by ikirill** [comment]
I think this package might violate "Curated - no obsolete, renamed, forked or randomly hacked packages", specifically /obsolete/ and /randomly hacked/, so I'm not sure I want to do that—I stopped being active here quite a while ago and that probably won't change.
