### ISSUE TITLE
use of obsolete functions

### ISSUE THREAD

**Issue by soonhokong** [ikirill/irony-eldoc#5]
Hi,

I'm using GNU Emacs 25.0.50.1 (on Ubuntu-12.04) and found some problems in irony-eldoc.el file. It gives me the following errors:
- `eldoc error: (void-function async-flag)`
- `eldoc error: (void-function remove-if-not)`

I think a possible fix is
- replace `remove-if-not` with `cl-remove-if-not`
- replace `lexical-let` with `let`

at least, this fixes it on my machine.

**Comment by aport** [comment]
Confirming. This fixes the eldoc errors for me as well.

**Comment by mambolevis** [comment]
Compiling no file at Fri May  6 22:00:02 2016
Warning (bytecomp): ‘(callback-thing (cdr thing))’ is a malformed function
Warning (bytecomp): reference to free variable ‘callback-thing’
Warning (bytecomp): reference to free variable ‘async-flag’
Warning (bytecomp): assignment to free variable ‘matches-available’
Warning (bytecomp): assignment to free variable ‘async-flag’
Warning (bytecomp): reference to free variable ‘matches-available’
Warning (bytecomp): the following functions are not known to be defined: remove-if-not,
    lexical-let, async-flag, matches-available

**Comment by nickbroon** [comment]
@ikirill Can you merge @josteink fix for this?

**Comment by ikirill** [comment]
Merged in #9.
